services:
  backend:
    image: arpithanms/to-do-app-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:Setup@db:5432/todo_db
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    image: arpithanms/to-do-app-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Setup
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
