name: Deploy To-D App

on:
  push:
  branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 3.24.135.216
          username: ubuntu
          key: ${{ sercrets.EC2_SSH_KEY }}
          scripts: |
            cd ~/to-do-app
            git pull origin main
            docker-compose down
            docker-compose up -d --build
